use_frameworks!

# 推荐继续使用 传统的 pod
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'

target 'PoporFMDB_Example' do
  pod 'PoporFMDB', :path => '../'

  target 'PoporFMDB_Tests' do
    inherit! :search_paths

  end
  
end

target 'PoporFMDBMac' do
    pod 'PoporFMDB', :path => '../'

end
